network_device:
  walk:
  - 1.3.6.1.2.1.1
  - 1.3.6.1.2.1.2
  - 1.3.6.1.2.1.31.1.1.1
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
    help: The time (in hundredths of a second) since the network management portion
      of the system was last re-initialized. - 1.3.6.1.2.1.1.3
  - name: sysName
    oid: 1.3.6.1.2.1.1.5
    type: DisplayString
  - name: ifPhysAddress
    oid: 1.3.6.1.2.1.2.2.1.6
    type: PhysAddress48
    help: The interface's address at its protocol sub-layer - 1.3.6.1.2.1.2.2.1.6
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifAdminStatus
    oid: 1.3.6.1.2.1.2.2.1.7
    type: gauge
    help: The desired state of the interface - 1.3.6.1.2.1.2.2.1.7
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifOperStatus
    oid: 1.3.6.1.2.1.2.2.1.8
    type: gauge
    help: The current operational state of the interface - 1.3.6.1.2.1.2.2.1.8
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifInDiscards
    oid: 1.3.6.1.2.1.2.2.1.13
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifInErrors
    oid: 1.3.6.1.2.1.2.2.1.14
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifInUnknowProtos
    oid: 1.3.6.1.2.1.2.2.1.15
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifOutDiscards
    oid: 1.3.6.1.2.1.2.2.1.19
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifOutErrors
    oid: 1.3.6.1.2.1.2.2.1.20
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifInOctets
    oid: 1.3.6.1.2.1.2.2.1.10
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifInUcastPkts
    oid: 1.3.6.1.2.1.2.2.1.11
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifInMulticastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.2
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifInBroadcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.3
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifOutOctets
    oid: 1.3.6.1.2.1.2.2.1.16
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifOutUcastPkts
    oid: 1.3.6.1.2.1.2.2.1.17
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifOutMulticastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.4
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifOutBroadcastPkts
    oid: 1.3.6.1.2.1.31.1.1.1.5
    type: counter
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifHighSpeed
    oid: 1.3.6.1.2.1.31.1.1.1.15
    type: gauge
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifType
      oid: 1.3.6.1.2.1.2.2.1.3
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: ifAlias
    oid: 1.3.6.1.2.1.31.1.1.1.18
    type: DisplayString
    indexes:
    - labelname: ifDescr
      type: gauge
    lookups:
    - labels:
      - ifDescr
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels:
      - ifDescr
      labelname: ifIndex
      oid: 1.3.6.1.2.1.2.2.1.1
      type: DisplayString
  - name: sysObjectID
    oid: 1.3.6.1.2.1.1.2
    type: DisplayString



